[build-system]
requires = ["setuptools>=61.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "radar_parser"
version = "0.0.0"
description = "RADAR parser"
authors = [{name="lemon girls"}]

[tool.setuptools.packages.find]
where = ["src"]
